version: '3.8'

services:
  app:
    container_name: bookmanager
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: >
      sh -c "npm run init-db && node dist/app.js"

  dev:
    container_name: bookmanager-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "9229:9229"

  test:
    container_name: bookmanager-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm test
